basket_app/urls.py
from basket_app import views
from django.urls import path

from django.conf import settings
from django.conf.urls.static import static

app_name= "basket_app"

urlpatterns = [
    path("login/",views.user_login,name="login"),
    path("logout/",views.user_logout,name="logout"),
    path('category/<slug:slug>/',views.ProductView.as_view(), name='product'),
    path('add-to-cart/<int:pk>/',views.add_to_cart, name='add-to-cart'),
    path('cart/',views.CartView.as_view(), name='cart'),
    path('increase_qty/<int:pk>/',views.increase_qty, name='increase-qty'),
    path('decrease_qty/<int:pk>/',views.decrease_qty, name='decrease-qty'),
    path('remove_product/<int:pk>/',views.remove_product, name='remove-product'),
    path('fillup/',views.Orderform.as_view(), name='fillup'),
    path('order/',views.OrderView.as_view(), name='order'),
    path('ordered/<int:pk>/',views.OrderSummary.as_view(), name='orderdetail'),
    # path("category/<str:cname>",views.categories,name="category"),

    
]

bigbasket/urls.py
from django.contrib import admin
from django.urls import path,include
from basket_app import views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index.as_view(), name='index'),
    path('',views.base.as_view(), name='base'),
    path('sign-up/',views.signup, name='sign_up'),
    path("test/",views.test,name="test"), #added
    path("getUsers/",views.getUsers,name="getUsers"), #added
    path('basket_app/',include("basket_app.urls",namespace="basket_app")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

basket_app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

# Create your models here.

class Receiver(models.Model):
    recname= models.CharField(max_length=50,blank=True,null=False)
    address= models.CharField(max_length=256,blank=True,null=False)
    phone= models.CharField(max_length=10,blank=True,null=False)

    def __str__(self):
        return self.recname

class Product(models.Model):
    pname= models.CharField(max_length=256)
    category= models.ForeignKey("Category",on_delete=models.CASCADE)
    ppic= models.ImageField(upload_to="product_images",null=True)
    price= models.PositiveIntegerField()
    amount= models.CharField(max_length=20)

    def __str__(self):
        return self.pname

    def get_absolute_url(self):
        return reverse("product", kwargs={"slug": self.slug})
    
    def get_add_to_cart_url(self):
        return reverse("add-to-cart", kwargs={"slug": self.slug})
    

class Category(models.Model):
    cname= models.CharField(max_length=256)
    cpic= models.ImageField(upload_to="category_images",null=True,blank=True)
    slug= models.SlugField()

    def __str__(self):
        return self.cname

class Cart(models.Model):
    product= models.ForeignKey("Product",on_delete=models.CASCADE, null=True)
    customer= models.ForeignKey("auth.User",on_delete=models.CASCADE, null=True)
    qty= models.PositiveIntegerField(default=1)

    def __str__(self):
        return str(self.product.pname)+' '+str(self.customer)

    def finalprice(self):
        return self.product.price*self.qty

class Order(models.Model):
    customer= models.ForeignKey("auth.user", on_delete=models.CASCADE, null=True)
    receiver= models.ForeignKey("Receiver",on_delete=models.CASCADE,null=True)
    order_date= models.DateField(null=True) 
    arrival_date= models.DateField(null=True)

    def __str__(self):
        return str(self.pk)

class OrderItem(models.Model):
    order= models.ForeignKey("Order", on_delete=models.CASCADE, null=True)
    product= models.ForeignKey("Product", on_delete=models.CASCADE, null=True)
    qty= models.PositiveIntegerField(default=1)

    def __str__(self):
        return str(self.order.pk)+' '+self.product.pname

    def finalprice(self):
        return self.product.price*self.qty
# class ProductCustomer(models.Model):
#     product= models.ForeignKey("Product",on_delete=models.CASCADE)
#     customer= models.ForeignKey("Customer",on_delete=models.CASCADE)
#     qty= models.PositiveIntegerField(default=0)

#     def __str__(self):
#         return self.product.pname

basket_app/forms.py
from django import forms
from django.contrib.auth.models import User
from django.forms.widgets import PasswordInput
from basket_app.models import Receiver

class CustomerForm(forms.ModelForm):
    password= forms.CharField(widget=PasswordInput)

    class Meta():
        model= User
        fields= ('username','password','email')

class OrderForm(forms.ModelForm):
    class Meta():
        model= Receiver
        fields= ('recname','phone','address')

    def __init__(self, *args, **kwargs):
        super(OrderForm, self).__init__(*args, **kwargs)
        self.fields['recname'].required = True
        self.fields['phone'].required = True
        self.fields['address'].required = True

basket_app/views.py
from django.shortcuts import render, get_object_or_404, redirect
from basket_app.forms import CustomerForm,OrderForm

from django.conf import settings
from django.utils import timezone
import datetime
  
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required

from django.http import JsonResponse

from django.views.generic import (View,TemplateView,ListView,DetailView,CreateView)
from .models import *
# Create your views here.

def test(request):     #added
	return render (request,'test.html')

def getUsers(request):   #added
    queryset = Category.objects.filter().order_by('-id')[:3]
    return JsonResponse({"category": list(queryset.values())})


class base(ListView):  
    template_name= 'base.html'
    model= Category
    context_object_name= "cat"

class index(ListView):
    template_name= 'index.html'
    model= Category
    context_object_name= "cat"

    def get_context_data(self,**kwargs):
        user= self.request.user
        context= super().get_context_data(**kwargs)

        if user.is_authenticated:
            context["cat"]= Category.objects.all
            context["count"]= Cart.objects.filter(customer=user).count()
        else: 
            context["cat"]= Category.objects.all
        return context



class ProductView(ListView):
    template_name= 'product.html'
    model= Product
    context_object_name= "prod"

    def get_context_data(self, **kwargs):
        slug= self.kwargs.get("slug")
        category= Category.objects.get(slug=slug)
        
        products= Product.objects.filter(category=category)
        context= super().get_context_data(**kwargs)

        context["products"]= products
        context["cat"]= Category.objects.all
        context["category"]= category
        context["count"]= Cart.objects.filter(customer= self.request.user).count()

        return context

class CartView(ListView):
    template_name= 'cart.html'
    model= Cart
    context_object_name= "cart_item"

    def get_context_data(self,**kwargs):
        context= super().get_context_data(**kwargs)
        context["count"]= Cart.objects.filter(customer= self.request.user).count()
        context["cat"]= Category.objects.all

        if Cart.objects.filter(customer= self.request.user).count()==0:
            context["check"]=True
        else:
            context["cartproducts"]= Cart.objects.filter(customer= self.request.user)


            cart= Cart.objects.filter(customer= self.request.user)
            total= 0 
            for c in cart:
                total= total + c.finalprice()

            context["total"]= total

        return context

class OrderView(ListView):
    template_name= 'order.html'
    model= Order

    def get_context_data(self,**kwargs):
        context= super().get_context_data(**kwargs)

        context["cat"]= Category.objects.all
        context["count"]= Cart.objects.filter(customer= self.request.user).count()
            
        if Order.objects.filter(customer= self.request.user).count()==0:
            context["check"]=True
        else:
            order= Order.objects.filter(customer= self.request.user)
            context["orderr"]= order

            for x in order:
                item= OrderItem.objects.filter(order= x)
                context["items"]= item

                total= 0 
                for c in item:
                    total= total + c.finalprice()

            context["total"]= total

        return context

class OrderSummary(DetailView):
    template_name= 'ordered.html'
    model= Order
    context_object_name= "orderr"

    def get_context_data(self,**kwargs):
        context= super().get_context_data(**kwargs)

        context["cat"]= Category.objects.all
        context["count"]= Cart.objects.filter(customer= self.request.user).count()
            
        if Order.objects.filter(customer= self.request.user).count()==0:
            context["check"]=True
        else:
            order= Order.objects.filter(customer= self.request.user)
            
            for x in order:
                item= OrderItem.objects.filter(order= x)
                context["items"]= item

                total= 0 

            for c in item:
                total= total + c.finalprice()

            context["total"]= total

        return context

# Functionalities
def add_to_cart(request,pk):
    product= get_object_or_404(Product, pk=pk)
    slug= product.category.slug

    cart_list= Cart.objects.filter(product=product, customer=request.user)

    if cart_list.exists():
        cart= cart_list[0]
        cart.qty = cart.qty + 1

        cart.save()
        
    else:
        cart_item= Cart.objects.create(product=product, customer=request.user)
        cart_item.save()

    return redirect('basket_app:product', slug= slug)

def increase_qty(request,pk):
    product= get_object_or_404(Product, pk=pk)
    cartproduct= Cart.objects.filter(customer=request.user, product=product)

    cart= cartproduct[0] 
    cart.qty = cart.qty + 1
    cart.save()

    return redirect('basket_app:cart')

def decrease_qty(request,pk):
    product= get_object_or_404(Product, pk=pk)
    cartproduct= Cart.objects.filter(customer=request.user, product=product)

    cart= cartproduct[0] 
    
    if cart.qty == 1:
        cart.delete()
        
    else:
        cart.qty = cart.qty - 1
        cart.save()

    return redirect('basket_app:cart')

def remove_product(request,pk):
    product= get_object_or_404(Product, pk=pk)
    cartproduct= Cart.objects.filter(customer=request.user, product=product)

    cart= cartproduct[0] 
    cart.delete()

    return redirect('basket_app:cart')
# End Of Functionalities

# Login, Logout, Signup, Forms
@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

class Orderform(CreateView):
    model = Receiver
    form_class = OrderForm
    template_name = 'basket_app/fillupform.html'
    def get_context_data(self,**kwargs):
        context= super().get_context_data(**kwargs)
        context["count"]= Cart.objects.filter(customer= self.request.user).count()
        return context
    def post(self,request):
        receiver = OrderForm(data=request.POST)
        print("lal")
        if receiver.is_valid():
            r = receiver.save(commit = False)
            r.save()
            cartobjects= Cart.objects.filter(customer=request.user)

            today= datetime.date.today()
            tdelta= datetime.timedelta(days=1)
            tday= today
            today= today + tdelta
            
            order= Order.objects.create(customer=request.user,receiver=r,arrival_date= today,order_date= tday)
            for cp in cartobjects:
                order_item= OrderItem.objects.create(order=order,product=cp.product,qty=cp.qty)
                order_item.save()
            Cart.objects.filter(customer=request.user).delete()
            return redirect('basket_app:order')
        else:
            print("Invalid Form")

            print(receiver.errors)
            return redirect('basket_app:fillup')

def signup(request):

    registered = False

    if request.method == "POST":
        customer_form = CustomerForm(data=request.POST)

        if customer_form.is_valid():
            user = customer_form.save()
            user.set_password(user.password)
            user.save()

            registered=True
            login(request,user)
            return HttpResponseRedirect(reverse('index'))

        else:
            print(customer_form.errors)
    
    else:
        customer_form = CustomerForm()

    return render(request, 'basket_app/register.html', {'customer_form':customer_form, 'registered':registered})

def user_login(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request,username=username, password=password)

        if user:
            login(request,user)
            return HttpResponseRedirect(reverse('index'))

        else:
            print("Someone tried to login and failed!!!")
            print("Username: {} and Password: {}".format(username,password))

            return HttpResponse("invalid login details supplied!!!")

    else:
        return render(request, 'basket_app/login.html', {})

# End Of Login, Logout, Signup, Forms

basket_app/templates/basket_app/basket_app_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href= "{% static 'css/basket.css' %}">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w=="crossorigin="anonymous" referrerpolicy="no-referrer" />
        <title>FRESH BASKET</title>
    </head>
    <body>
        <div class="taskbar">
            <div class="part-1">
                <a href="{% url 'index' %}"class="logo-name">BIG BASKET</a>
            </div>

            <div class="part-2">
                {% if user.is_authenticated %}
                    <div class="cart-sec">
                        <a href="{% url 'basket_app:cart' %}"><i class="fas fa-shopping-cart cart-logo"></i></a>   
                        <div class="circle">{{count}}</div> 
                    </div>   
                    <a class="tb-link" href="{% url 'basket_app:logout' %}">Logout</a>
                    <a class="tb-link" href="{% url 'basket_app:order' %}">Orders</a>
                    <p class="tb-link">Welcome, <span class="italic">{{user.username}}</span></p>
                {% else %}
                    <a class="tb-link" href="{% url 'basket_app:login' %}">Login</a>
                    <a class="tb-link" href="{% url 'sign_up' %}">SIGN UP</a>
                {% endif %}
            </div>
        </div>

        {% block body_block %}
        {% endblock %}
    </body>
</html>

basket_app/templates/basket_app/fillupform.html
{% extends "basket_app/basket_app_base.html" %}
{% block body_block %}
{% load widget_tweaks %}
{% load static %}
    <form class="fillup" method="POST">
        <h1 class="form-heading">Delivery Details</h1>
        {% csrf_token %}
        <div class="input-field">
            <h1 class="input-heading">Name</h1>
            {% render_field form.recname class="input-box" placeholder="Name" %}
        </div>
        <div class="input-field">
            <h1 class="input-heading">Phone No</h1>
            {% render_field form.phone minlength="10" maxlength="10" class="input-box" placeholder="Phone Number" %}
        </div>
        <div class="input-field">
            <h1 class="input-heading">Address</h1>
            {% render_field form.address class="input-box" placeholder="Deliver to Address" %}
        </div>
            
        <input type="submit" class="btn input-field" value="Submit">
    </form>
{% endblock %}

basket_app/templates/basket_app/login.html
{% extends "basket_app/basket_app_base.html" %}
{% block body_block %}
{% load static %}
    <form action="{% url 'basket_app:login' %}" class="login input-form" method="POST">
        <h1 class="form-heading">Login</h1>
        {% csrf_token %}
        <div class="input-field">
            <h2 class="input-heading">Username</h2>
            <input type="text" name="username" class="input-box" placeholder="Enter your username">
        </div>
        <div class="input-field">    
            <h2 class="input-heading">Password</h2>
            <input type="password" name= "password" class="input-box" placeholder="Enter your password">
        </div>
        <input type="submit" class="btn input-field" value="LOGIN">
    </form>
{% endblock %}

basket_app/templates/basket_app/register.html
{% extends "basket_app/basket_app_base.html" %}
{% block body_block %}
{% load widget_tweaks %}
{% load static %}      
    <form class="sign-up input-form" method="POST">
        <h1 class="form-heading">Sign Up</h1>
        {% csrf_token %}
        <div class="input-field">
            <h1 class="input-heading">{{ customer_form.username.label }}</h1>
            {% render_field customer_form.username class="input-box" placeholder="Enter username" %}
        </div>
        <div class="input-field">
            <h1 class="input-heading">{{ customer_form.password.label }}</h1>
            {% render_field customer_form.password class="input-box" placeholder="Enter password" %}
        </div>
        <div class="input-field">
            <h1 class="input-heading">{{ customer_form.email.label }}</h1>
            {% render_field customer_form.email class="input-box" placeholder="Enter email" %}
        </div>
        <input type="submit" class="btn input-field" value="Register">
    </form>
{% endblock %}