basket_app/urls.py
from basket_app import views
from django.urls import path

from django.conf import settings
from django.conf.urls.static import static

app_name= "basket_app"

urlpatterns = [
    path("login/",views.user_login,name="login"),
    path("logout/",views.user_logout,name="logout"),
    path('category/<slug:slug>/',views.ProductView.as_view(), name='product'),
    path('add-to-cart/<int:pk>/',views.add_to_cart, name='add-to-cart'),
    path('cart/',views.CartView.as_view(), name='cart'),
    path('increase_qty/<int:pk>/',views.increase_qty, name='increase-qty'),
    path('decrease_qty/<int:pk>/',views.decrease_qty, name='decrease-qty'),
    path('remove_product/<int:pk>/',views.remove_product, name='remove-product'),
    path('fillup/',views.Orderform.as_view(), name='fillup'),
    path('order/',views.OrderView.as_view(), name='order'),
    path('ordered/<int:pk>/',views.OrderSummary.as_view(), name='orderdetail'),
    # path("category/<str:cname>",views.categories,name="category"),

    
]

bigbasket/urls.py
from django.contrib import admin
from django.urls import path,include
from basket_app import views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index.as_view(), name='index'),
    path('',views.base.as_view(), name='base'),
    path('sign-up/',views.signup, name='sign_up'),
    path("test/",views.test,name="test"), #added
    path("getUsers/",views.getUsers,name="getUsers"), #added
    path('basket_app/',include("basket_app.urls",namespace="basket_app")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/cart.html
{% extends 'base.html' %}
{% block base %}
{% load static %}
    <div class="container target">
        <h1 class="heading">CART SUMMARY</h1>
        {% if check %}
            <p class="warning">Your cart is empty</p>
            <a href="{% url 'index' %}">
                <button class="btn green"><i class="fas fa-arrow-left redirect"></i>Start Shopping</button>
            </a>
        {% else %}
            <div class="options">
                <a href="{% url 'index' %}">
                    <button class="btn-1 green"><i class="fas fa-arrow-left redirect-2"></i> Continue Shopping</button>
                </a>

                <a href="{% url 'basket_app:fillup' %}">
                    <button class="btn-1">Place Order <i class="fas fa-arrow-right redirect-2"></i></button>
                </a>
            </div>
            {% for cp in cartproducts %}
                <div class="cart-item">
                    <img src="{{cp.product.ppic.url}}" class="cartpic">    
                    <div class="sec"> 
                        <div class="sec-1">
                            <div class="info">
                                <p class="product-name desc">{{cp.product.pname}}</p> 
                                <div class="price-sec">
                                    <p class="price">{{cp.product.price}}</p>
                                    <i class="fas fa-rupee-sign rupee-1"></i>
                                    <p class="amount carta">/{{cp.product.amount}}</p>
                                </div>
                            </div>
                        
                            <div class="qty">
                                <a href="{% url 'basket_app:decrease-qty' pk=cp.product.pk %}"><i class="fas fa-minus symbol"></i></a>
                                <p class="symbol">{{cp.qty}}</p>
                                <a href="{% url 'basket_app:increase-qty' pk=cp.product.pk %}"><i class="fas fa-plus symbol"></i></a>
                            </div>

                            <div class="price-sec finalprice">
                                <p class="price">{{cp.finalprice}}</p>
                                <i class="fas fa-rupee-sign rupee-1"></i>
                            </div>
                        </div>

                        <div class="sec-2">
                            <a href="{% url 'basket_app:remove-product' pk=cp.product.pk %}">
                                <input type="submit" class="btn remove" value="Remove From Cart">
                            </a>
                        </div>
                    </div>
                </div>
            {% endfor %}
            
            <div class="price-sec total">
                <p class="totalprice">Subtotal: <span class="totalprice">{{total}}</span></p>
                <i class="fas fa-rupee-sign rupee-2"></i>
            </div>

            <a href="#home" class="scroll-up-btn">
                <i class="fas fa-arrow-up"></i> 
            </a>
        {% endif %}
    </div>
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% block base %}
{% load static %}
        <div class="back-container target">
            <!-- <div class="main-back">
                <img src="{% static 'logo/background.jpg' %}" class="background">
            </div> -->
            <div class="back-info">
                <div class="z">
                    <h1 class="back-info-1">Welcome to FRESH BASKET</h1>
                </div>
                <div class="z">
                    <h1 class="back-info-2">Your one stop shop for all your grocery needs.</h1>
                </div>
                {% if user.is_authenticated %}

                {% else %}
                    <div class="z">
                        <h1 class="back-info-3">Login or SignUp to start shopping</h1>
                    </div>
                {% endif %}
            </div>
        </div>
        {% if user.is_authenticated %}
            <div class="container target">
                <fieldset class="parent">
                    <legend class="heading">Categories</legend>
                    {% for category in cat %}
                    <a href="{% url 'basket_app:product' category.slug %}">
                        <fieldset class="child">
                            <legend class="category-heading">{{category.cname}}</legend>
                            
                        </fieldset>
                    </a>
                    {% endfor %}
                </fieldset>
            </div>
        {% else %}
        
        {% endif %}
{% endblock %}

templates/order.html
{% extends 'base.html' %}
{% block base %}
{% load static %}
    <div class="container target">
        <h1 class="heading">YOUR ORDERS</h1>
        {% if check %}
            <p class="warning">You currently have no orders!!!</p>
            <a href="{% url 'index' %}">
                <button class="btn green"><i class="fas fa-arrow-left redirect"></i>Start Shopping</button>
            </a>
        {% else %}
            <div class="all-orders">
                {% for order in orderr %}
                    <a href="{% url 'basket_app:orderdetail' pk=order.pk %}">
                        <div class="order-info">
                            <h1 class="order"><span class="field">Name:</span> {{order.receiver.recname}}</h1>
                            <h1 class="order"><span class="field">Order Date:</span> {{order.order_date}}</h1>
                            <h1 class="order"><span class="field">Arriving Date:</span> {{order.order_date}}</h1>
                        </div>
                    </a>
                {% endfor %}
            </div>
        {% endif %}

        <a href="#home" class="scroll-up-btn">
            <i class="fas fa-arrow-up"></i> 
        </a>
    </div>
{% endblock %}

templates/ordered.html
{% extends 'base.html' %}
{% block base %}
{% load static %}
<div class="container target">
    <h1 class="heading">ORDER SUMMARY</h1>
    <div class="ordered-info">
        <h1 class="order"><span class="field">Name:</span> {{orderr.receiver.recname}}</h1>
        <h1 class="order"><span class="field">Phone:</span> {{orderr.receiver.phone}}</h1>
        <h1 class="order"><span class="field">Address:</span> {{orderr.receiver.address}}</h1>

        <h1 class="order"><span class="field">Order Date:</span> {{orderr.order_date}}</h1>
        <h1 class="order"><span class="field">Arriving Date:</span> {{orderr.order_date}}</h1>
    </div>

    
    <div class="ordered-item">
        <div class="column-names">
            <div class="pname style-2">Product Name</div>
            <div class="pmrp style-1">MRP(in Rs.)</div>
            <div class="pqty style-1">Qty</div>
            <div class="pprice style-3">Price(in Rs.)</div>
        </div>
        <div class="underline"></div>
        {% for item in items %}
            <div class="item-info">
                <h1 class="pname style-2 common">{{item.product.pname}} <span class="pamount">/{{item.product.amount}}</span></h1>
                <h1 class="pmrp style-1 common">{{item.product.price}}</h1>
                <h1 class="pqty style-1 common">{{item.qty}}</h1>
                <h1 class="pprice style-3 common">{{item.finalprice}}</h1>
            </div>
            <div class="underline"></div>
        {% endfor %}
        <h1 class="style-4">Grand Total: {{total}} Rs.</h1>

        <a href="{% url 'basket_app:order' %}">
            <button class="btn green"><i class="fas fa-arrow-left redirect"></i>Back to Orders</button>
        </a>
    </div>

    <a href="#home" class="scroll-up-btn">
        <i class="fas fa-arrow-up"></i> 
    </a>
</div>
{% endblock %}

templates/product.html
{% extends 'base.html' %}
{% block base %}
    <div class="container target">
        <fieldset class="parent">
            <legend class="heading">{{category.cname}}</legend>
            {% for product in products %}
                <div class="child">
                    <img src="{{product.ppic.url}}" class="prodpic">
                    <h1 class="product-heading">{{product.pname}}</h1>
                    <div class="sub-sec">
                        <div class="price-sec">
                            <p class="price">{{product.price}}</p>
                            <i class="fas fa-rupee-sign rupee-1"></i>
                        </div>
                        <p class="amount">per.{{product.amount}}</p>
                    </div>
                    <a href="{% url 'basket_app:add-to-cart' pk=product.pk %}" class="btn-container">
                        <button class="add-btn">Add To Cart</button>
                    </a>
                </div>
            {% endfor %}
        </fieldset>
        <a href="#home" class="scroll-up-btn">
            <i class="fas fa-arrow-up"></i> 
        </a>
    </div>
{% endblock %}

templates/test.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>Hello, world!</title>
</head>

<body>
    <h1>Hello, world!</h1>

    <script src="https://code.jquery.com/jquery-3.6.0.js"
        integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
    <table class="table table-dark">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">First</th>
                <th scope="col">Last</th>
                <th scope="col">Handle</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <th scope="row">1</th>
                <td>Mark</td>
                <td>Otto</td>
                <td>@mdo</td>
            </tr>
        <tbody id="display">

        </tbody>

        </tbody>
    </table>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
   
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
</body>

</html>

<script>
    $(document).ready(function () {

        setInterval(function () {

            $.ajax({
                type: 'GET',
                url: "{% url 'getUsers' %}",

                success: function (response) {
                    
                    // console.log(response)

                    $("#display").empty();
                    
                    for (var key in response.category) {
                        var temp = "<tr><th scope='row'>" + response.category[key].cname+ "</th></tr>";
                        $("#display").append(temp);
                    }

                },
                error: function (response) {
                    alert("No data found");
                }
            });
        }, 1000);

    });
</script>